### ISSUE TITLE
pdfGenerator.generatePDF("FILE_NAME.pdf");

### ISSUE THREAD

**Issue by webappdevlopers** [kariot/pdf-invoice-generator#13]
pdfGenerator.generatePDF("FILE_NAME.pdf"); getting crash here

**Comment by webappdevlopers** [comment]
getting crash

**Comment by kariot** [comment]
Can you attach a stack trace if you have any?

**Comment by amirhoseein63** [comment]
same problem

**Comment by mnguyen081002** [comment]
pdfGenerator.generatePDF("FILE_NAME.pdf") throw this error

```
FATAL EXCEPTION: main
Process: com.example.sportstore, PID: 15210
java.lang.ClassCastException: android.graphics.drawable.VectorDrawable cannot be cast to android.graphics.drawable.BitmapDrawable
	at me.kariot.invoicegenerator.utils.InvoiceGenerator.initInvoiceHeader(InvoiceGenerator.kt:150)
	at me.kariot.invoicegenerator.utils.InvoiceGenerator.generatePDF(InvoiceGenerator.kt:121)
	at com.example.sportstore.OrderAdapter.lambda$onBindViewHolder$1$com-example-sportstore-OrderAdapter(OrderAdapter.java:137)
	at com.example.sportstore.OrderAdapter$$ExternalSyntheticLambda1.onClick(D8$$SyntheticClass:0)
	at android.view.View.performClick(View.java:7448)
	at android.view.View.performClickInternal(View.java:7425)
	at android.view.View.access$3600(View.java:810)
	at android.view.View$PerformClick.run(View.java:28305)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```
